### ISSUE TITLE
No data recieved

### ISSUE THREAD

**Issue by CallumMcK** [poml88/LibreWrist#11]
Have tried with 2 separate LibreLink accounts, but get ‘no data received since 999 minutes’ on both.

not sure where I am going wrong?

app says ‘connected’ in green at the bottom after inputting email and password.

**Comment by poml88** [comment]
Sorry for this. I am traveling right now, but can look at it soon.
Do you just see the default data in the background?
The easiest would be if you could email me a temporary password for one of the llu accounts that do not work. That way I can test it with the debug console.

**Comment by CallumMcK** [comment]
yes just see the default in the background. I'll email you

**Comment by poml88** [comment]
Almost fixed, mmol/l should be working now, as well as the eu2 region. Some small fixes to be done on the green box and the red line....

**Comment by poml88** [comment]
Seems to working now. Closing this. Thanks for your help.
