### ISSUE TITLE
Apple Watch app won't open

### ISSUE THREAD

**Issue by julio8a** [poml88/LibreWrist#4]
WatchOS 11.0.1
iOS 18.0.1 

Phone app works fine. 

Apple Watch app doesn't open at all. When I click it, I get a brief loader with the app icon, then it just closes every time.

**Comment by poml88** [comment]
Hi again, thanks for your report. I would have some questions:
Did it ever work with iOS 18 / watchOS 11.
Did you have some change recently, any updates of OS?
Or a sensor change, so it might be confused with some data from the previous sensor?
Did you try to completely remove the watchOS app from the watch? The two ways I know are either on the watch app overview view or using the „watch“ app on the phone.
Ah, and: are you maybe on mmol/l? 
do the other apps work? LibreLinkUp, LibreWatch etc.?
Is it Libre3? US version?
Did you choose any particular watch face and complication?

librewrist phone and watch apps use almost the same code. 

Thanks for your help!

**Comment by julio8a** [comment]
Did it ever work with iOS 18 / watchOS 11.
**I installed it very recently when I was on 18.0.1 and 11.0.1** so I can't say.

Did you have some change recently, any updates of OS?
**No**
Or a sensor change, so it might be confused with some data from the previous sensor?
**No**

Did you try to completely remove the watchOS app from the watch? The two ways I know are either on the watch app overview view or using the „watch“ app on the phone.
**Okay, I tried this (uninstalled it from watch) then reinstalled. After reinstall I get the "Warning" message and description. After I click "Accept" it says "no creditials (yet)" message. After I go back to mobile app, I click connect. The credential message goes away and it says no data since 9999. After a few seconds the watch app crashes. Trying to launch it again doesn't bring anything up and just continues to crash every time I try to open it.**

Ah, and: are you maybe on mmol/l?
**mg/dl**

do the other apps work? LibreLinkUp, LibreWatch etc.?
**both `LibreLinkUp` and `LibreWatch` work fine**

Is it Libre3? US version?
**Libre3, US**

Did you choose any particular watch face and complication?
**It crashes weather it's a complication or just opening the app from home screen.**

**Comment by poml88** [comment]
Interesting, thanks, so the app starts, but when it receives its first data it throws exception.
Question: could you possibly give me access to your follower account to test on Xcode here? You could change your password to something for a short while and then back.

or what you could do is to invite my support email address as a follower and then delete this follower account anytime.

At the moment I cannot reproduce this here. I asked a friend as well, everything fine there too.

**Comment by julio8a** [comment]
I can invite you to LibreLinkUp

**Comment by poml88** [comment]
Ok, let's try!

**Comment by julio8a** [comment]
What's the best way to get your email address?

**Comment by poml88** [comment]
I just tried exactly the procedure you described above .. no problem here.
Is it version 1.0.9.25? You can see it after re-installation, before sending credentials on the donate view...

**Comment by julio8a** [comment]
I am on v1.0.8.24

I checked the app store and 1.0.8 is the latest (1 day ago).

**Comment by poml88** [comment]
Oh, sorry, email is librewrist a t cmdline d o t net. It's also on the GitHub front page and in the phone app...

Oh, my bad, indeed. .8.24 is the last on the App Store.

**Comment by julio8a** [comment]
Sent!

**Comment by poml88** [comment]
Received. Trying to connect...

**Comment by poml88** [comment]
Interesting, it tells me "no data since 540 mins". Is that our time difference?
9 hours, should be. Yes, indeed. Interesting. The graph ends at 13:25, that is correct.

**Comment by julio8a** [comment]
I am PST 1:25pm (13:25) right now, which would be true if you are in Europe?

**Comment by poml88** [comment]
Another bug: It continues to use my authtoken. I did send new credentials, but I still see my own data...

**Comment by poml88** [comment]
I re-installed the watch app -- now your data. The bad news: It is working fine. :-/

**Comment by poml88** [comment]
Maybe you can try my follower account. Can send you the password.

**Comment by julio8a** [comment]
Ah!!! Bummer! Okay, I'll do some more troubleshooting. Will try to uninstall the entire app and start all over! Will keep you posted.

**Comment by julio8a** [comment]
> Maybe you can try my follower account. Can send you the password.

Sure, what would work best to get the password from you?

**Comment by poml88** [comment]
Email? I see you have a profile on your GitHub page with a website which has contact data?

**Comment by poml88** [comment]
Or even easier: Do you have a second email address? Just make yourself another follower account, that is what I just did...

**Comment by julio8a** [comment]
That form on my website works! :)

**Comment by poml88** [comment]
Ok, it says the form was sent.
I will have to go to sleep soon... Approaching 11pm...

**Comment by julio8a** [comment]
I got it. I'll do some testing today and will post back with any updates. Have a good night!

**Comment by poml88** [comment]
Well, thanks to you: One bug fixed. I am clearing the auth_token now when new credentials are received by the watch!

**Comment by poml88** [comment]
Maybe, if you would use TestFlight, I could get a crash report via TestFlight. I think TestFlight offers this.
I will add the latest version to TestFlight. The link to TestFlight is on this page.
But be aware: There are some bugs with Apple when switching between AppStore and TestFlight builds. Some things might be strange, like complications / widgets and would require a reboot of the device...

https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs

https://help.apple.com/xcode/mac/current/#/deve2819c518

Seem it would work even with the App Store app... You have to opt in... Then I will get a report.

**Comment by julio8a** [comment]
I did turn on those settings. I also downloaded one of the analytics files from yesterday. See attached (bug type 309):
[LibreWristWatch Watch App-2024-10-15-203654.txt](https://github.com/user-attachments/files/17399530/LibreWristWatch.Watch.App-2024-10-15-203654.txt)

**Comment by poml88** [comment]
Great, thanks! I will check it!
Meanwhile I got an email from someone who has a similar problem: The iOS app is closing, just as your watch app.
I wonder if in the TestFlight builds there is even more info. Would it be possible you try the testflight build?
BTW Build 1.0.9.26 should be out, could you try this please as well?

**Comment by julio8a** [comment]
Okay, I did install the testFlight app and made sure the app and watch app were on 1.0.9.26. 

The same thing happens when I open the watch app (only). It crashes after clicking `connect`. Not sure if there's anything else I need to do to send that crash report info or if you just see it at this point. I tried running the apple watch a few times to get a few crashes. :D

**Comment by poml88** [comment]
Ok, thanks a lot. I should see the crash report in xcode now. I am not at home right now, will do it asap.

**Comment by poml88** [comment]
Ok, as I thought: Normally this is an "index out of range", so if you try to read from an array a certain index and it does not exist it will throw exception. And as I thought it is in reloadLibreLinkUp. Good, now let's find where...

**Comment by poml88** [comment]
Hm, it seems that `let lastMeasurement = LibreLinkUpHistory.shared.libreLinkUpGlucose[0]` fails, so there is no index 0.

**Comment by poml88** [comment]
Strangely enough, I see 3 crash logs. But they are all from my Spanish speaking friend and all say they are from TestFlight. 
So, you Julio, you sent me a log as well, I did not yet figure out how to see this in Xcode.

**Comment by julio8a** [comment]
Is there anything I need to do in the TestFlight app to send the crash report? I didn't do anything other than open the watch app and watch it crash a few times.

**Comment by poml88** [comment]
Very strange, I do not see any crash logs of the watch app. I will check that! Or google it to find out.
anyway, I added a check that the index [0] really exists. There will be a new version on TestFlight soon (waiting for Apple's approval). Version 1.0.10.27. Can you please try it and tell me what you see, if you see anything?
Thanks for your help!

**Comment by julio8a** [comment]
Sounds good, I'll keep an eye on TestFlight for `.27`. 🤞

**Comment by poml88** [comment]
Google says it can take up to 1 day for crash logs to appear in Xcode. So maybe tomorrow. But I think it is the same issue, because phone and watch are using the same code from a shared swift file.

**Comment by poml88** [comment]
Hi, the TestFlight .27 is available now. The crash should be gone. But the question is: What happens now? I do not understand why the array was empty.... And why was it not a problem when I followed your data?

**Comment by julio8a** [comment]
Same thing. It says no data for 999 min. After a few seconds it crashes. Trying to run the app again on the watch shows the loading icon for half a second and keeps crashing.

**Comment by poml88** [comment]
It is still the watch app, right? Can you try to remove and reinstall the watch app and look on the debug info it is indeed the right version?

**Comment by poml88** [comment]
In principle it makes no sense at all, because it is the same library for watch and phone. For the other bug reporter it is the phone app crashing. And in that crash report it was clearly that array.
I did receive a crash report from the watch from someone now, but there is not much info in there...
There must be a way to debug this, I have no idea right now...

**Comment by julio8a** [comment]
Yeah, it's just the watch app crashing. Everything works great on the phone app. After installing the .27 update from TestFlight I uninstalled the watch app and reinstalled it. Before I hit the connect button again on the phone app I checked the version on the watch app to make sure it was .27 and it was. Then I hit the connect button and the crashing started.

**Comment by julio8a** [comment]
> In principle it makes no sense at all, because it is the same library for watch and phone. For the other bug reporter it is the phone app crashing. And in that crash report it was clearly that array. I did receive a crash report from the watch from someone now, but there is not much info in there... There must be a way to debug this, I have no idea right now...

So strange. I've still been using the LibeWatch on my watch, as that app sends glucose data to HealthApp, so I would primarily still use that one until LibreWrist can send glucose data to HealthApp and it works on my watch. :D 

Oh my phone, I use the LibreWrist app and the widget which work great!

**Comment by poml88** [comment]
Maybe your issue is a different one than I thought. But I have only one crash report yet and that one does not tell me anything. Maybe it is a certain UI setting on your watch.

**Comment by julio8a** [comment]
uh, not sure what I would update on my side to get this to work. I think for now I'm okay using LibreWatch on my watch and the widget/app from LibreWrist on my phone. Like I mentioned earlier, I still need to open LibreWatch on my watch to send my glucose data to Apple Health App. 

Maybe as more updates come it'll magically start working without knowing why. lol

**Comment by poml88** [comment]
There is no crash report yet for 1.0.10.27. Maybe it will be there tomorrow.
From what I can see it is something with the UI... I'll go through the file again.
I will keep an eye open. Maybe, if you can try a new TestFlight version from Time to time and I will get more crash reports I will discover what happens. Maybe also other people will report the same issue.
Sorry about that. Will look into that HealthKit thing in the meantime.

**Comment by julio8a** [comment]
Sounds good. I'll keep using TestFlight and keep trying it as new releases come out. Hopefully, something will show up on your end at some point.

**Comment by poml88** [comment]
Last questions: 
Did the watch app ever work, or never?
Did you actually try to reboot the watch?⌚️

**Comment by julio8a** [comment]
The watch app has never worked since installation. 

I just tried to reboot my Apple watch just now and got the same crash when launching the LibreWrist watch app.

**Comment by poml88** [comment]
Ok. Your watch is in English?
Any particular settings for the UI?
:-)

**Comment by julio8a** [comment]
Yes, my watch is in English. 

What settings in the UI would you be referring to? anything specific?

**Comment by poml88** [comment]
No, unfortunately no concrete idea.
Strangely enough, the TestFlight statistics still report 0 crashes. Either it will come later, or never, or in your case something else is crashing, but not the app, maybe something in watchOS, so the crash is not attributed to the app.

**Comment by poml88** [comment]
Hi, some more info: I do not get any TestFlight crashes from you. I do not know why. Can you check your TestFlight settings that logs are indeed shared?
What does appear in Xcode is the crashlog you also send above as a txt file. I looked at it again. It is something strange with the UI. It seems it cannot paint the graph or so. 
Up to now you are the only one reporting this. It could have something to do with watchOS11, because there appress a function 

`_UIGraphicsBeginImageContextWithOptions ` in the crashlog that is deprecated in watchOS 11. However, deprecated does not mean broken and it seems everyone else is using watchOS 11, too.

Indeed it might go away magically by some OS or Xcode updates. In any case, it would be good if those TestFlight crashlogs would reach me.

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: LibreWristWatch Watch App [727]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1dfe374c __exceptionPreprocess + 160 (NSException.m:249)
1   libobjc.A.dylib               	0x1c287180 objc_exception_throw + 72 (objc-exception.mm:356)
2   Foundation                    	0x1cffb6c4 0x1c7d9000 + 8529604
3   UIKitCore                     	0x3b38e374 _UIGraphicsBeginImageContextWithOptions + 544 (UIGraphics.m:407)
4   PepperUICore                  	0x3cc64d28 -[PUICActivityIndicatorView _updateContentImage] + 260 (PUICActivityIndicatorView.m:300)
5   PepperUICore                  	0x3cc64e1c -[PUICActivityIndicatorView setColor:] + 76 (PUICActivityIndicatorView.m:316)
6   SwiftUI                       	0x4462189c 0x43cf4000 + 9623708
7   SwiftUI                       	0x43e72ae8 0x43cf4000 + 1567464
8   SwiftUI                       	0x43e6d638 0x43cf4000 + 1545784
9   SwiftUICore                   	0x42619a58 0x41e0b000 + 8448600
10  SwiftUI                       	0x445016b4 0x43cf4000 + 8443572
11  SwiftUI                       	0x43e838f8 0x43cf4000 + 1636600
12  SwiftUI                       	0x43e87078 0x43cf4000 + 1650808
13  SwiftUICore                   	0x421d500c 0x41e0b000 + 3973132
14  SwiftUICore                   	0x421d40d8 0x41e0b000 + 3969240
15  SwiftUI                       	0x43e6c7c4 0x43cf4000 + 1542084
16  SwiftUI                       	0x43e861d8 0x43cf4000 + 1647064
17  SwiftUI                       	0x43e8554c 0x43cf4000 + 1643852
18  SwiftUICore                   	0x42378d28 0x41e0b000 + 5692712
19  SwiftUICore                   	0x42377c14 0x41e0b000 + 5688340
20  SwiftUICore                   	0x421cf558 0x41e0b000 + 3949912
21  SwiftUICore                   	0x42377300 0x41e0b000 + 5686016
22  SwiftUICore                   	0x4237706c 0x41e0b000 + 5685356
23  SwiftUI                       	0x43e66924 0x43cf4000 + 1517860
24  SwiftUICore                   	0x42039cbc 0x41e0b000 + 2288828
25  SwiftUI                       	0x43e793dc 0x43cf4000 + 1594332
26  AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
27  AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
28  AttributeGraph                	0x371b067c AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 680 (ag-graph.cc:1510)
29  AttributeGraph                	0x3719ba64 AGGraphGetValue + 240 (AGGraph.mm:723)
30  SwiftUI                       	0x43d26db8 0x43cf4000 + 208312
31  SwiftUI                       	0x44501d88 0x43cf4000 + 8445320
32  SwiftUI                       	0x43cf8374 0x43cf4000 + 17268
33  AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
34  AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
35  AttributeGraph                	0x371b067c AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 680 (ag-graph.cc:1510)
36  AttributeGraph                	0x3719f9f4 AGGraphGetInputValue + 276 (AGGraph.mm:705)
37  SwiftUICore                   	0x424f58d0 0x41e0b000 + 7252176
38  SwiftUICore                   	0x420abda4 0x41e0b000 + 2756004
39  SwiftUICore                   	0x42274f78 0x41e0b000 + 4628344
40  SwiftUICore                   	0x42274ca4 0x41e0b000 + 4627620
41  SwiftUICore                   	0x42278074 0x41e0b000 + 4640884
42  SwiftUICore                   	0x42458414 0x41e0b000 + 6607892
43  SwiftUICore                   	0x42274044 0x41e0b000 + 4624452
44  SwiftUICore                   	0x422647f0 0x41e0b000 + 4560880
45  SwiftUICore                   	0x4226473c 0x41e0b000 + 4560700
46  SwiftUICore                   	0x42258a24 0x41e0b000 + 4512292
47  AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
48  AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
49  AttributeGraph                	0x371b067c AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 680 (ag-graph.cc:1510)
50  AttributeGraph                	0x3719f9f4 AGGraphGetInputValue + 276 (AGGraph.mm:705)
51  SwiftUICore                   	0x424f58d0 0x41e0b000 + 7252176
52  SwiftUICore                   	0x420abda4 0x41e0b000 + 2756004
53  SwiftUICore                   	0x42274f78 0x41e0b000 + 4628344
54  SwiftUICore                   	0x42274ca4 0x41e0b000 + 4627620
55  SwiftUICore                   	0x42278074 0x41e0b000 + 4640884
56  SwiftUICore                   	0x42458414 0x41e0b000 + 6607892
57  SwiftUICore                   	0x42274044 0x41e0b000 + 4624452
58  SwiftUICore                   	0x422647f0 0x41e0b000 + 4560880
59  SwiftUICore                   	0x4226fc24 0x41e0b000 + 4607012
60  SwiftUICore                   	0x42258a24 0x41e0b000 + 4512292
61  AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
62  AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
63  AttributeGraph                	0x371b04b8 AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 228 (ag-graph.cc:1476)
64  AttributeGraph                	0x3719f9f4 AGGraphGetInputValue + 276 (AGGraph.mm:705)
65  SwiftUICore                   	0x420d829c 0x41e0b000 + 2937500
66  SwiftUICore                   	0x41e86370 0x41e0b000 + 504688
67  SwiftUICore                   	0x42248760 0x41e0b000 + 4446048
68  SwiftUICore                   	0x422484dc 0x41e0b000 + 4445404
69  SwiftUICore                   	0x424594f4 0x41e0b000 + 6612212
70  SwiftUICore                   	0x420d8da4 0x41e0b000 + 2940324
71  SwiftUICore                   	0x41e88744 0x41e0b000 + 513860
72  SwiftUICore                   	0x4227687c 0x41e0b000 + 4634748
73  SwiftUICore                   	0x4227661c 0x41e0b000 + 4634140
74  SwiftUICore                   	0x424594f4 0x41e0b000 + 6612212
75  SwiftUICore                   	0x420d8da4 0x41e0b000 + 2940324
76  SwiftUICore                   	0x41e88744 0x41e0b000 + 513860
77  SwiftUICore                   	0x4227687c 0x41e0b000 + 4634748
78  SwiftUICore                   	0x4227661c 0x41e0b000 + 4634140
79  SwiftUICore                   	0x424594f4 0x41e0b000 + 6612212
80  SwiftUICore                   	0x420d8da4 0x41e0b000 + 2940324
81  SwiftUICore                   	0x41e88744 0x41e0b000 + 513860
82  SwiftUICore                   	0x4227687c 0x41e0b000 + 4634748
83  SwiftUICore                   	0x4227661c 0x41e0b000 + 4634140
84  SwiftUICore                   	0x424594f4 0x41e0b000 + 6612212
85  SwiftUICore                   	0x420d830c 0x41e0b000 + 2937612
86  SwiftUICore                   	0x41e86370 0x41e0b000 + 504688
87  SwiftUICore                   	0x42248760 0x41e0b000 + 4446048
88  SwiftUICore                   	0x422484dc 0x41e0b000 + 4445404
89  SwiftUICore                   	0x424594f4 0x41e0b000 + 6612212
90  SwiftUICore                   	0x420d8da4 0x41e0b000 + 2940324
91  SwiftUICore                   	0x41e88744 0x41e0b000 + 513860
92  SwiftUICore                   	0x4227687c 0x41e0b000 + 4634748
93  SwiftUICore                   	0x4227661c 0x41e0b000 + 4634140
94  SwiftUICore                   	0x424594f4 0x41e0b000 + 6612212
95  SwiftUICore                   	0x42098b94 0x41e0b000 + 2677652
96  SwiftUICore                   	0x4224fbb0 0x41e0b000 + 4475824
97  AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
98  AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
99  AttributeGraph                	0x371b067c AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 680 (ag-graph.cc:1510)
100 AttributeGraph                	0x3719ba64 AGGraphGetValue + 240 (AGGraph.mm:723)
101 SwiftUICore                   	0x42264498 0x41e0b000 + 4560024
102 SwiftUICore                   	0x422543a8 0x41e0b000 + 4494248
103 AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
104 AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
105 AttributeGraph                	0x371b067c AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 680 (ag-graph.cc:1510)
106 AttributeGraph                	0x3719ba64 AGGraphGetValue + 240 (AGGraph.mm:723)
107 SwiftUICore                   	0x4226f914 0x41e0b000 + 4606228
108 SwiftUICore                   	0x41f4bb8c 0x41e0b000 + 1313676
109 AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
110 AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
111 AttributeGraph                	0x371b067c AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, unsigned int, AGSwiftMetadata const*, unsigned char&, long) + 680 (ag-graph.cc:1510)
112 AttributeGraph                	0x3719ba64 AGGraphGetValue + 240 (AGGraph.mm:723)
113 SwiftUICore                   	0x423e58a0 0x41e0b000 + 6138016
114 SwiftUICore                   	0x41f4b2d0 0x41e0b000 + 1311440
115 AttributeGraph                	0x3719d164 AG::Graph::UpdateStack::update() + 544 (ag-graph-update.cc:583)
116 AttributeGraph                	0x3719e4c8 AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 428 (ag-graph-update.cc:712)
117 AttributeGraph                	0x3719c754 AG::Subgraph::update(unsigned int) + 832 (ag-subgraph.cc:758)
118 SwiftUICore                   	0x423615ac 0x41e0b000 + 5596588
119 SwiftUICore                   	0x42618df8 0x41e0b000 + 8445432
120 SwiftUICore                   	0x42616d58 0x41e0b000 + 8437080
121 SwiftUI                       	0x4451ef4c 0x43cf4000 + 8564556
122 SwiftUI                       	0x4451efb0 0x43cf4000 + 8564656
123 UIKitCore                     	0x3b2e64ac -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2540 (UIView.m:20400)
124 QuartzCore                    	0x1edef378 CA::Layer::layout_if_needed(CA::Transaction*) + 408 (CALayer.mm:10944)
125 QuartzCore                    	0x1ede4fa8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 120 (CALayer.mm:2638)
126 QuartzCore                    	0x1edddbe8 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 428 (CAContextInternal.mm:2613)
127 QuartzCore                    	0x1ee30bb4 CA::Transaction::commit() + 652 (CATransactionInternal.mm:420)
128 QuartzCore                    	0x1ee3b5e4 CA::Transaction::flush_as_runloop_observer(bool) + 84 (CATransactionInternal.mm:928)
129 UIKitCore                     	0x3bf64f54 _UIApplicationFlushCATransaction + 48 (UIApplication.m:3311)
130 UIKitCore                     	0x3b751fac _UIUpdateSequenceRun + 72 (_UIUpdateSequence.mm:136)
131 UIKitCore                     	0x3bedebec schedulerStepScheduledMainSection + 168 (_UIUpdateScheduler.m:1171)
132 UIKitCore                     	0x3beddff4 runloopSourceCallback + 84 (_UIUpdateScheduler.m:1334)
133 CoreFoundation                	0x1dfe4f6c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24 (CFRunLoop.c:1950)
134 CoreFoundation                	0x1dff99a8 __CFRunLoopDoSource0 + 172 (CFRunLoop.c:1994)
135 CoreFoundation                	0x1df9315c __CFRunLoopDoSources0 + 232 (CFRunLoop.c:2031)
136 CoreFoundation                	0x1df339fc __CFRunLoopRun + 796 (CFRunLoop.c:2949)
137 CoreFoundation                	0x1df78d40 CFRunLoopRunSpecific + 532 (CFRunLoop.c:3414)
138 GraphicsServices              	0x25290844 GSEventRunModal + 160 (GSEvent.c:2196)
139 UIKitCore                     	0x3b41c7a8 -[UIApplication _run] + 856 (UIApplication.m:3820)
140 UIKitCore                     	0x3b3d459c UIApplicationMain + 124 (UIApplication.m:5472)
141 WatchKit                      	0x44fa4f14 WKApplicationMain + 124 (WKApplicationMain.m:20)
142 WatchKit                      	0x44fad83c WKApplicationExtensionMain + 380 (main.m:133)
143 SwiftUI                       	0x44259c8c 0x43cf4000 + 5659788
144 SwiftUI                       	0x440e796c 0x43cf4000 + 4143468
145 LibreWristWatch Watch App     	0x23c5088 static LibreWristWatch_Watch_AppApp.$main() + 24 (LibreWristWatchApp.swift:0)
146 LibreWristWatch Watch App     	0x23c5088 main + 36
147 dyld                          	0x25a5a614 start + 1528 (dyldMain.cpp:1334)

Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x000000002546ec94 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x0000000025b4f3c8 pthread_kill + 208 (pthread.c:1721)
2   libsystem_c.dylib             	0x000000001e3ee53c abort + 124 (abort.c:0)
3   libc++abi.dylib               	0x0000000023f1b3a8 abort_message + 132 (abort_message.cpp:78)
4   libc++abi.dylib               	0x0000000023f0af9c demangling_terminate_handler() + 296 (cxa_default_handlers.cpp:77)
5   libobjc.A.dylib               	0x000000001c28a7d4 _objc_terminate() + 124 (objc-exception.mm:496)
6   libc++abi.dylib               	0x0000000023f1a964 std::__terminate(void (*)()) + 12 (cxa_handlers.cpp:59)
7   libc++abi.dylib               	0x0000000023f1d770 __cxa_rethrow + 144 (cxa_exception.cpp:648)
8   libobjc.A.dylib               	0x000000001c29e124 objc_exception_rethrow + 40 (objc-exception.mm:399)
9   CoreFoundation                	0x000000001df78e04 CFRunLoopRunSpecific + 728 (CFRunLoop.c:3430)
10  GraphicsServices              	0x0000000025290844 GSEventRunModal + 160 (GSEvent.c:2196)
11  UIKitCore                     	0x000000003b41c7a8 -[UIApplication _run] + 856 (UIApplication.m:3820)
12  UIKitCore                     	0x000000003b3d459c UIApplicationMain + 124 (UIApplication.m:5472)
13  WatchKit                      	0x0000000044fa4f14 WKApplicationMain + 124 (WKApplicationMain.m:20)
14  WatchKit                      	0x0000000044fad83c WKApplicationExtensionMain + 380 (main.m:133)
15  SwiftUI                       	0x0000000044259c8c 0x43cf4000 + 5659788
16  SwiftUI                       	0x00000000440e796c 0x43cf4000 + 4143468
17  LibreWristWatch Watch App     	0x00000000023c5088 static LibreWristWatch_Watch_AppApp.$main() + 24 (LibreWristWatchApp.swift:0)
18  LibreWristWatch Watch App     	0x00000000023c5088 main + 36
19  dyld                          	0x0000000025a5a614 start + 1528 (dyldMain.cpp:1334)
```

**Comment by julio8a** [comment]
updating to 11.1 right now! 🤞

**Comment by julio8a** [comment]
OMG IT'S WORKING!!! after the update.

**Comment by poml88** [comment]
Ok, Great. Self fixing bugs are the best.

yes the healthkit… I am out hiking, can’t program right now… :)

**Comment by julio8a** [comment]
@poml88 I would rather hike too! Enjoy!
